import Head from 'next/head';
import Navbar from '@/components/Navbar';
import ReferSteps from '@/components/ReferSteps';
import Stores from '@/components/Stores';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Company Referral</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <ReferSteps />
      <Stores />
      <Footer />
    </>
  );
}
